name: Stream on GitHub

on:
  workflow_dispatch:

jobs:
  run-stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install streamlink

      - name: Setup Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Run Server and Show Link
        run: |
          python app.py &
          sleep 10
          # Ngrok-কে বাধ্য করা হচ্ছে যাতে এটি সরাসরি ডাটা পাঠায়
          ngrok http 7860 --log=stdout --host-header=rewrite
